from pathlib import Path


DIRETORIO_RAIZ = Path(__file__).resolve().parent.parent
DIRETORIO_DADOS = DIRETORIO_RAIZ / "dados"
DIRETORIO_RESULTADOS = DIRETORIO_RAIZ / "resultados"
DIRETORIO_GRAFICOS = DIRETORIO_RAIZ / "graficos"

CAMINHO_ARQUIVO_ZIP = DIRETORIO_DADOS / "canal_24ghz.zip"
CAMINHO_BASE_PROCESSADA = DIRETORIO_DADOS / "base_canal_24ghz.npz"

URL_BASE_UCI = "https://archive.ics.uci.edu/static/public/480/2%2B4%2Bghz%2Bindoor%2Bchannel%2Bmeasurements.zip"

PREFIXO_DIRETORIO_MEDICOES = "Measurements_Upload/Measurements_Upload/"
EXTENSAO_ARQUIVO_MEDICAO = ".csv"
SEPARADOR_CSV = ";"
PREFIXO_LINHA_COMENTARIO = "#"
CODIFICACAO_ARQUIVOS = "utf-8-sig"

INDICE_COLUNA_FREQUENCIA = 0
INDICE_COLUNA_REAL_S21 = 3
INDICE_COLUNA_IMAGINARIA_S21 = 4

QUANTIDADE_AMBIENTES = 4
QUANTIDADE_POSICOES_POR_AMBIENTE = 196
QUANTIDADE_LINHAS_POSICOES = 14
QUANTIDADE_COLUNAS_POSICOES = 14
QUANTIDADE_REPETICOES_POR_POSICAO = 10
QUANTIDADE_MEDICOES_POR_AMBIENTE = 1960
QUANTIDADE_MEDICOES_TOTAL = 7840
QUANTIDADE_PONTOS_FREQUENCIA = 601
QUANTIDADE_CANAIS_S21 = 2
QUANTIDADE_GRUPOS_TOTAL = QUANTIDADE_AMBIENTES * QUANTIDADE_POSICOES_POR_AMBIENTE

FREQUENCIA_INICIAL_HZ = 2400000000.0
FREQUENCIA_FINAL_HZ = 2500000000.0
LARGURA_FAIXA_HZ = FREQUENCIA_FINAL_HZ - FREQUENCIA_INICIAL_HZ
PASSO_FREQUENCIA_HZ = LARGURA_FAIXA_HZ / (QUANTIDADE_PONTOS_FREQUENCIA - 1)
TOLERANCIA_FREQUENCIA_HZ = 1.0

TAMANHO_BLOCO_DOWNLOAD_BYTES = 1048576

CHAVE_FREQUENCIAS = "frequencias"
CHAVE_S21 = "s21"
CHAVE_CLASSES = "classes"
CHAVE_AMBIENTES = "ambientes"
CHAVE_POSICOES = "posicoes"
CHAVE_REPETICOES = "repeticoes"
CHAVE_GRUPOS = "grupos"
CHAVE_ARQUIVOS = "arquivos"

CODIGO_ERRO_DESCONHECIDO = 1000
CODIGO_ERRO_ARGUMENTO_INVALIDO = 1001
CODIGO_ERRO_CONVERSAO_DADOS = 1002

CODIGO_ERRO_ARQUIVO_NAO_ENCONTRADO = 2001
CODIGO_ERRO_CAMINHO_NAO_E_ARQUIVO = 2002
CODIGO_ERRO_ARQUIVO_ZIP_INVALIDO = 2003
CODIGO_ERRO_NENHUMA_MEDICAO_ENCONTRADA = 2004
CODIGO_ERRO_CAMINHO_INTERNO_INVALIDO = 2005
CODIGO_ERRO_AMBIENTE_DESCONHECIDO = 2006
CODIGO_ERRO_POSICAO_INVALIDA = 2007
CODIGO_ERRO_REPETICAO_INVALIDA = 2008
CODIGO_ERRO_LINHA_CSV_INVALIDA = 2009
CODIGO_ERRO_LEITURA_MEDICAO = 2010

CODIGO_ERRO_NOME_AMBIENTE_INVALIDO = 3001
CODIGO_ERRO_CLASSE_INVALIDA = 3002
CODIGO_ERRO_CAMINHO_MEDICAO_INVALIDO = 3003
CODIGO_ERRO_GRUPO_INVALIDO = 3004
CODIGO_ERRO_DIMENSAO_INVALIDA = 3005
CODIGO_ERRO_QUANTIDADE_PONTOS_INVALIDA = 3006
CODIGO_ERRO_VALOR_NUMERICO_INVALIDO = 3007
CODIGO_ERRO_GRADE_FREQUENCIAS_INVALIDA = 3008
CODIGO_ERRO_CRIACAO_MEDICAO = 3009

CODIGO_ERRO_BASE_INVALIDA = 4001
CODIGO_ERRO_CHAVE_AUSENTE = 4002
CODIGO_ERRO_FORMATO_BASE_INVALIDO = 4003
CODIGO_ERRO_CONTEUDO_BASE_INVALIDO = 4004
CODIGO_ERRO_BASE_COMPLETA_INVALIDA = 4005
CODIGO_ERRO_SALVAMENTO_BASE = 4006
CODIGO_ERRO_CARREGAMENTO_BASE = 4007
CODIGO_ERRO_PROCESSAMENTO_BASE = 4008

CODIGO_ERRO_URL_INVALIDA = 5001
CODIGO_ERRO_CRIACAO_DIRETORIO = 5002
CODIGO_ERRO_DOWNLOAD_BASE = 5003
CODIGO_ERRO_ARQUIVO_BAIXADO_INVALIDO = 5004
CODIGO_ERRO_REMOCAO_ARQUIVO = 5005

DICIONARIO_CLASSES_POR_DIRETORIO = {
    "Corridor_rm155_7.1": 0,
    "Lab139_7.1": 1,
    "Main_Lobby_7.1": 2,
    "Sport_Hall_7.1": 3
}

DICIONARIO_NOMES_POR_CLASSE = {
    0: "Corredor",
    1: "Laboratório",
    2: "Saguão principal",
    3: "Ginásio"
}