from pathlib import Path


DIRETORIO_RAIZ = Path(__file__).resolve().parent.parent
DIRETORIO_DADOS = DIRETORIO_RAIZ / "dados"
DIRETORIO_RESULTADOS = DIRETORIO_RAIZ / "resultados"
DIRETORIO_GRAFICOS = DIRETORIO_RAIZ / "graficos"
DIRETORIO_MODELOS = DIRETORIO_RAIZ / "modelos"

CAMINHO_ARQUIVO_ZIP = DIRETORIO_DADOS / "canal_24ghz.zip"
CAMINHO_BASE_PROCESSADA = DIRETORIO_DADOS / "base_canal_24ghz.npz"
CAMINHO_BASE_PREPARADA = DIRETORIO_DADOS / "base_preparada_24ghz.npz"

URL_BASE_UCI = "https://archive.ics.uci.edu/static/public/480/2%2B4%2Bghz%2Bindoor%2Bchannel%2Bmeasurements.zip"

PREFIXO_DIRETORIO_MEDICOES = "Measurements_Upload/Measurements_Upload/"
EXTENSAO_ARQUIVO_MEDICAO = ".csv"
SEPARADOR_CSV = ";"
PREFIXO_LINHA_COMENTARIO = "#"
CODIFICACAO_ARQUIVOS = "utf-8-sig"

INDICE_COLUNA_FREQUENCIA = 0
INDICE_COLUNA_REAL_S21 = 3
INDICE_COLUNA_IMAGINARIA_S21 = 4

QUANTIDADE_AMBIENTES = 4
QUANTIDADE_POSICOES_POR_AMBIENTE = 196
QUANTIDADE_LINHAS_POSICOES = 14
QUANTIDADE_COLUNAS_POSICOES = 14
QUANTIDADE_REPETICOES_POR_POSICAO = 10
QUANTIDADE_MEDICOES_POR_AMBIENTE = 1960
QUANTIDADE_MEDICOES_TOTAL = 7840
QUANTIDADE_PONTOS_FREQUENCIA = 601
QUANTIDADE_CANAIS_S21 = 2
QUANTIDADE_GRUPOS_TOTAL = QUANTIDADE_AMBIENTES * QUANTIDADE_POSICOES_POR_AMBIENTE

FREQUENCIA_INICIAL_HZ = 2400000000.0
FREQUENCIA_FINAL_HZ = 2500000000.0
LARGURA_FAIXA_HZ = FREQUENCIA_FINAL_HZ - FREQUENCIA_INICIAL_HZ
PASSO_FREQUENCIA_HZ = LARGURA_FAIXA_HZ / (QUANTIDADE_PONTOS_FREQUENCIA - 1)
TOLERANCIA_FREQUENCIA_HZ = 1.0

PROPORCAO_TREINO = 0.70
PROPORCAO_VALIDACAO = 0.15
PROPORCAO_TESTE = 0.15
SEMENTE_ALEATORIA = 42

EPSILON_MAGNITUDE = 1.0E-12
DESVIO_PADRAO_MINIMO = 1.0E-12

MLP_CAMADAS_OCULTAS = (32,16)
MLP_TAMANHO_LOTE = 128
MLP_TAXA_APRENDIZADO = 0.001
MLP_REGULARIZACAO = 0.0001
MLP_MAXIMO_EPOCAS = 50
MLP_PACIENCIA = 7
MLP_MELHORA_MINIMA = 1.0E-4

CNN_CANAIS_PRIMEIRA_CAMADA = 16
CNN_CANAIS_SEGUNDA_CAMADA = 32
CNN_CANAIS_TERCEIRA_CAMADA = 64
CNN_TAMANHO_POOLING_ADAPTATIVO = 16
CNN_NEURONIOS_CAMADA_DENSA = 64
CNN_DROPOUT = 0.20
CNN_TAMANHO_LOTE = 128
CNN_TAXA_APRENDIZADO = 0.001
CNN_DECAIMENTO_PESOS = 0.0001
CNN_MAXIMO_EPOCAS = 50
CNN_PACIENCIA = 7
CNN_MELHORA_MINIMA = 1.0E-4

TAMANHO_BLOCO_DOWNLOAD_BYTES = 1048576

CHAVE_FREQUENCIAS = "frequencias"
CHAVE_S21 = "s21"
CHAVE_CLASSES = "classes"
CHAVE_AMBIENTES = "ambientes"
CHAVE_POSICOES = "posicoes"
CHAVE_REPETICOES = "repeticoes"
CHAVE_GRUPOS = "grupos"
CHAVE_ARQUIVOS = "arquivos"

CHAVE_INDICES_TREINO = "indices_treino"
CHAVE_INDICES_VALIDACAO = "indices_validacao"
CHAVE_INDICES_TESTE = "indices_teste"

CHAVE_GRUPOS_TREINO = "grupos_treino"
CHAVE_GRUPOS_VALIDACAO = "grupos_validacao"
CHAVE_GRUPOS_TESTE = "grupos_teste"

CHAVE_REPRESENTACAO_CARTESIANA = "representacao_cartesiana"
CHAVE_REPRESENTACAO_POLAR = "representacao_polar"
CHAVE_REPRESENTACAO_TEMPORAL = "representacao_temporal"
CHAVE_ATRASOS = "atrasos"

CHAVE_MEDIA_CARTESIANA = "media_cartesiana"
CHAVE_DESVIO_CARTESIANA = "desvio_cartesiana"
CHAVE_MEDIA_POLAR = "media_polar"
CHAVE_DESVIO_POLAR = "desvio_polar"
CHAVE_MEDIA_TEMPORAL = "media_temporal"
CHAVE_DESVIO_TEMPORAL = "desvio_temporal"

CHAVE_DADOS_NORMALIZADOS = "dados_normalizados"
CHAVE_MEDIAS = "medias"
CHAVE_DESVIOS = "desvios"

CODIGO_ERRO_DESCONHECIDO = 1000
CODIGO_ERRO_ARGUMENTO_INVALIDO = 1001
CODIGO_ERRO_CONVERSAO_DADOS = 1002

CODIGO_ERRO_ARQUIVO_NAO_ENCONTRADO = 2001
CODIGO_ERRO_CAMINHO_NAO_E_ARQUIVO = 2002
CODIGO_ERRO_ARQUIVO_ZIP_INVALIDO = 2003
CODIGO_ERRO_NENHUMA_MEDICAO_ENCONTRADA = 2004
CODIGO_ERRO_CAMINHO_INTERNO_INVALIDO = 2005
CODIGO_ERRO_AMBIENTE_DESCONHECIDO = 2006
CODIGO_ERRO_POSICAO_INVALIDA = 2007
CODIGO_ERRO_REPETICAO_INVALIDA = 2008
CODIGO_ERRO_LINHA_CSV_INVALIDA = 2009
CODIGO_ERRO_LEITURA_MEDICAO = 2010

CODIGO_ERRO_NOME_AMBIENTE_INVALIDO = 3001
CODIGO_ERRO_CLASSE_INVALIDA = 3002
CODIGO_ERRO_CAMINHO_MEDICAO_INVALIDO = 3003
CODIGO_ERRO_GRUPO_INVALIDO = 3004
CODIGO_ERRO_DIMENSAO_INVALIDA = 3005
CODIGO_ERRO_QUANTIDADE_PONTOS_INVALIDA = 3006
CODIGO_ERRO_VALOR_NUMERICO_INVALIDO = 3007
CODIGO_ERRO_GRADE_FREQUENCIAS_INVALIDA = 3008
CODIGO_ERRO_CRIACAO_MEDICAO = 3009

CODIGO_ERRO_BASE_INVALIDA = 4001
CODIGO_ERRO_CHAVE_AUSENTE = 4002
CODIGO_ERRO_FORMATO_BASE_INVALIDO = 4003
CODIGO_ERRO_CONTEUDO_BASE_INVALIDO = 4004
CODIGO_ERRO_BASE_COMPLETA_INVALIDA = 4005
CODIGO_ERRO_SALVAMENTO_BASE = 4006
CODIGO_ERRO_CARREGAMENTO_BASE = 4007
CODIGO_ERRO_PROCESSAMENTO_BASE = 4008

CODIGO_ERRO_URL_INVALIDA = 5001
CODIGO_ERRO_CRIACAO_DIRETORIO = 5002
CODIGO_ERRO_DOWNLOAD_BASE = 5003
CODIGO_ERRO_ARQUIVO_BAIXADO_INVALIDO = 5004
CODIGO_ERRO_REMOCAO_ARQUIVO = 5005

CODIGO_ERRO_VETORES_DIVISAO_INVALIDOS = 6001
CODIGO_ERRO_GRUPO_COM_MULTIPLAS_CLASSES = 6002
CODIGO_ERRO_GRUPOS_INSUFICIENTES = 6003
CODIGO_ERRO_DIVISAO_INVALIDA = 6004
CODIGO_ERRO_CRIACAO_DIVISAO = 6005

CODIGO_ERRO_MATRIZ_S21_INVALIDA = 7001
CODIGO_ERRO_GERACAO_REPRESENTACAO = 7002
CODIGO_ERRO_GERACAO_ATRASOS = 7003

CODIGO_ERRO_MATRIZ_NORMALIZACAO_INVALIDA = 8001
CODIGO_ERRO_INDICES_NORMALIZACAO_INVALIDOS = 8002
CODIGO_ERRO_PARAMETROS_NORMALIZACAO_INVALIDOS = 8003
CODIGO_ERRO_NORMALIZACAO = 8004

CODIGO_ERRO_BASE_PREPARADA_INVALIDA = 9001
CODIGO_ERRO_PREPARACAO_EXPERIMENTOS = 9002
CODIGO_ERRO_SALVAMENTO_BASE_PREPARADA = 9003
CODIGO_ERRO_CARREGAMENTO_BASE_PREPARADA = 9004

CODIGO_ERRO_ANALISE_EXPLORATORIA = 10001
CODIGO_ERRO_SALVAMENTO_ANALISE = 10002
CODIGO_ERRO_BASES_INCOMPATIVEIS = 10003

CODIGO_ERRO_TREINAMENTO_MLP = 11001
CODIGO_ERRO_DADOS_MLP_INVALIDOS = 11002
CODIGO_ERRO_RESULTADO_MLP_INVALIDO = 11003
CODIGO_ERRO_SALVAMENTO_MLP = 11004

CODIGO_ERRO_TREINAMENTO_CNN = 12001
CODIGO_ERRO_DADOS_CNN_INVALIDOS = 12002
CODIGO_ERRO_RESULTADO_CNN_INVALIDO = 12003
CODIGO_ERRO_SALVAMENTO_CNN = 12004

DICIONARIO_CLASSES_POR_DIRETORIO = {
    "Corridor_rm155_7.1": 0,
    "Lab139_7.1": 1,
    "Main_Lobby_7.1": 2,
    "Sport_Hall_7.1": 3
}

DICIONARIO_NOMES_POR_CLASSE = {
    0: "Corredor",
    1: "Laboratório",
    2: "Saguão principal",
    3: "Ginásio"
}